# NumPy

Astyppe

In [4]:
D=23566
 

In [5]:
import numpy as np

In [7]:
M=np.array(D)

In [8]:
type(M)

numpy.ndarray

In [9]:
N=M.astype(int)

In [11]:
type(N)

numpy.ndarray

In [12]:
N


array(23566)

In [15]:
 M=[[[1,2,3,]]]

In [17]:
M=np.array(M)

In [18]:
M

array([[[1, 2, 3]]])

In [20]:
M.dtype

dtype('int32')

In [21]:
M.ndim

3

In [22]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [25]:
arang=np.arange(10)
arang

array([], dtype=int32)

In [36]:
matrix[2,2]

9

In [39]:
matrix[1,1]

5

In [40]:
matrix[:,2]

array([3, 6, 9])

In [42]:
matrix[:[1:2]]

SyntaxError: invalid syntax (2356803744.py, line 1)

In [44]:
matrix[1:3,1:3]

array([[5, 6],
       [8, 9]])

In [45]:
matrix[1:3,1:3]

array([[5, 6],
       [8, 9]])

In [51]:
matrix[1:2,1:3]

array([[5, 6]])

In [48]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Lambda

# Arange

# linSpace

In [57]:
line=np.linspace(2,5)

In [58]:
line

array([2.        , 2.06122449, 2.12244898, 2.18367347, 2.24489796,
       2.30612245, 2.36734694, 2.42857143, 2.48979592, 2.55102041,
       2.6122449 , 2.67346939, 2.73469388, 2.79591837, 2.85714286,
       2.91836735, 2.97959184, 3.04081633, 3.10204082, 3.16326531,
       3.2244898 , 3.28571429, 3.34693878, 3.40816327, 3.46938776,
       3.53061224, 3.59183673, 3.65306122, 3.71428571, 3.7755102 ,
       3.83673469, 3.89795918, 3.95918367, 4.02040816, 4.08163265,
       4.14285714, 4.20408163, 4.26530612, 4.32653061, 4.3877551 ,
       4.44897959, 4.51020408, 4.57142857, 4.63265306, 4.69387755,
       4.75510204, 4.81632653, 4.87755102, 4.93877551, 5.        ])

# Random

- rand
- randn

 - randint

In [70]:
 
mo=np.random.randint(20,50)

In [71]:
mo

26

In [72]:
 
mo=np.random.randint(20,50,5)

In [73]:
mo

array([26, 24, 28, 42, 31])

In [76]:
moh=np.random.rand(1,10)

In [77]:
moh

array([[0.86735009, 0.62302117, 0.8967768 , 0.65375793, 0.83672671,
        0.7140556 , 0.968796  , 0.81708477, 0.85744029, 0.72993001]])

In [80]:
mohi=np.random.rand(2,10)
mohi

array([[0.87635527, 0.96587882, 0.13113561, 0.65385909, 0.45261577,
        0.1767949 , 0.89989253, 0.65659353, 0.49581919, 0.28601867],
       [0.43028071, 0.93834142, 0.11654281, 0.78797355, 0.96462381,
        0.60169963, 0.56786245, 0.98895576, 0.83513478, 0.58066884]])

# Pandas

In [82]:
import pandas as pd

In [85]:
ser=pd.Series()

C:\Users\Dell\AppData\Local\Temp\ipykernel_14660\1876242370.py:1: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  ser=pd.Series()


In [86]:
ser

Series([], dtype: float64)

In [89]:
import warnings
warnings.filterwarnings('ignore')

In [90]:
ser


Series([], dtype: float64)

In [93]:

data=pd.DataFrame()

In [96]:
data.types

AttributeError: 'DataFrame' object has no attribute 'types'

In [97]:
type(data)

pandas.core.frame.DataFrame